Proyecto Spot-it Free/Controllers/DescubreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Proyecto_Spot_it_Free.Models;

namespace Proyecto_Spot_it_Free.Controllers
{
    public class DescubreController : Controller
    {
        private espotiEntities db = new espotiEntities();

        // GET: Descubre
        public ActionResult Index()
        {
            Descubre e = new Descubre();
            List<Cancion> k = new List<Cancion>();
            List<Disco> dk = new List<Disco>();
            List<Artista> at = new List<Artista>();



            for (int i = 0; i < e.CancionesID.Count(); i++)
            {
                int id = e.CancionesID[i];
                Cancion cs = db.Cancion.Where(x => x.Id == id).SingleOrDefault();
                k.Add(cs);
            }
            for (int i = 0; i < e.DiscosID.Count(); i++)
            {
                int id = e.DiscosID[i];
                var disco = db.Disco.Where(x => x.Id == id).FirstOrDefault();
                dk.Add(disco);
            }

            for (int i = 0; i < e.ArtistasID.Count(); i++)
            {
                string user = e.ArtistasID[i];
                var artistas = db.Artista.Where(x => x.Usuario1.Nick == user).FirstOrDefault();
                at.Add(artistas);
            }
            Descubre BBB = new Descubre(k, dk, at);
            return View(BBB);
        }
    }
}

Proyecto Spot-it Free/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title - Spot-It Free</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <!-- Para el reproductor de audio-->
    <script type="text/javascript" src="~/Content/Media/swfobject.js"></script>

    <link rel='stylesheet prefetch' href='https://fonts.googleapis.com/css?family=Open+Sans:600'>
    <link rel="stylesheet" href="~/Content/Style1.css">
    <link rel="stylesheet" href="~/Content/bootstrap.css">
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
    <style>
        h4 {
            color: gray;
            margin-right: 130px;
            margin-left: 400px;
        }

        player {
            margin-bottom: 20em;
        }

        li {
            float: left;
            padding: 5px;
        }

            li:last-child {
                float: right;
            }

        body {
            background-color: #393737;
        }
    </style>
</head>

    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">

                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @using (Html.BeginForm())
                    {
                        Usuario user = (Usuario)Session["Usuario"];
                        if (user == null || user.Validado == 0)
                        { }
                        if (user != null && user.Validado==1)
                        { <a href="~/Login/UserDashBoard"><img src="~/Images/Logo_mini.png" /></a>}
                    }
                    <!-- Html.ActionLink("Spot it Free", "Index", "Home", new { area = "" }, new { class = "navbar-brand" }) -->
                </div>

                @using (Html.BeginForm())
                {
                    Usuario user = (Usuario)Session["Usuario"];

                    if (user == null ||user.Validado==0)
                    { }

                    else
                    {
                        if (user.Tipo == 1)
                        {
                          <div class="navbar-collapse collapse">
                              <ul class="nav navbar-nav col-md-10">
                                  <li>@Html.ActionLink("Detalles", "Details", new { id = user.Nick })</li>
                                  <li>@Html.ActionLink("Explora", "Index", "Descubre")</li>
                                  <li> <a href="/Explora/Index?localidad=@user.Localidad"> Descubre</a></li>




                                  <div class="btn-group">
                                      <button type="button" class="btn btn-default btn-lg dropdown-toggle"
                                              data-toggle="dropdown">
                                          CRUD <span class="caret"></span>
                                      </button>

                                      <ul class="dropdown-menu" role="menu">
                                          <li>@Html.ActionLink("Usuarios", "Index", "Usuarios")</li>
                                          <li>@Html.ActionLink("Artistas", "Index", "Artistas")</li>
                                          <li>@Html.ActionLink("Listas", "Index", "Listas")</li>
                                          <li>@Html.ActionLink("Canciones", "Index", "Canciones")</li>
                                          <li>@Html.ActionLink("Discos", "Index", "Discos")</li>
                                          <li>@Html.ActionLink("Generos", "Index", "Generos")</li>
                                      </ul>
                                  </div>



                              </ul>

                          </div>
                        }

                        if (user.Tipo != 1)
                        {   
                            <div class="navbar-collapse collapse">
                                <ul class="nav navbar-nav col-md-10">
                                    <li>@Html.ActionLink("Mi perfil", "Details", "Usuarios", new { id = user.Nick }, new { })</li>
                                    <li>@Html.ActionLink("Explora", "Index", "Descubre")</li>
                                    <li> <a href="/Explora/Index?localidad=@user.Localidad"> Descubre</a></li>
                                    <li>
                                        <div style="margin-top:15px">

                                            <input type="text" id="busquedax" style="width:200px" placeholder="Artistas, Usuarios o Canciones" />
                                            <a href="#" onclick="myFunction()" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-zoom-in"></span>¡Buscar!</a>
                                        </div>
                                    </li>
                                    <li style="margin-left:10px;margin-top:15px;text-align:right; color:darkgrey">
                                        <div>
                                            Hola @user.Nick, @Html.ActionLink(" ¿cerrar sesión?", "CerrarSesion", "Login")
                                        </div>
                                    </li>



                                </ul>
                                @using (Html.BeginForm())
                                {
                                    if (Session["Usuario"] != null || user.Validado == 0)
                                    {



                                            <script>
                                                function myFunction() {
                                                    var busqueda = document.getElementById('busquedax').value;
                                                    var url = "/Busqueda/Index?SearchText=" + busqueda;
                                                    location.href = url;
                                                }

                                            </script> 
                                    }


                                }
                                </div>
                        }
                    }
                }


                @*
                    <div class="btn-group">
                        <div id="player">
                            <script type="text/javascript">
                                        var so = new SWFObject('/Content/Media/mediaplayer.swf','mpl','331','19','0');
                                        so.addParam('allowfullscreen','true');
                                        so.addVariable('displayheight','0');
                                        so.addVariable('file','/Content/Media/playlist1.xml');
                                        so.addVariable('height','19');
                                        so.addVariable('width','331');
                                        so.addVariable('frontcolor','0x444444');
                                        so.addVariable('backcolor','0xffffff');
                                        so.addVariable('lightcolor','0xfed136');
                                        so.addVariable('thumbsinplaylist','true');
                                        so.addVariable('repeat','true');
                                        so.addVariable('shuffle','false');
                                        so.addVariable('showeq','false');
                                        so.write('player');
                            </script>
                        </div>
                    </div>
                *@

            </div>

        </div>
        <br />
        <br />
        <br />
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Spot-It Free</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>